import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation/Navigation";
import { SessionProvider } from "next-auth/react";

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nowted",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSans.variable} flex bg-primary antialiased h-screen`}
      >
        <SessionProvider>
          <Navigation />
          <main className="basis-full flex">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
