import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Folders from "./components/navigation/Folders";
import More from "./components/navigation/More";
import Link from "next/link";

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nowted",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSans.variable} flex bg-primary antialiased h-screen`}
      >
        <nav className="xs:hidden lg:flex basis-[30%] py-6 text-secondary flex-col gap-7">
          <div className="flex flex-col gap-4 px-4">
            <div className="flex justify-between items-center">
              <Image
                src={"/logo.svg"}
                alt="Nowted logo"
                height={100}
                width={100}
              />
            </div>
            <button className="bg-[#242424] flex cursor-pointer rounded-xs">
              <Link
                href={"/new-note"}
                className="flex justify-center gap-2 p-2.5 basis-full"
              >
                <Image
                  src={"/plus.svg"}
                  alt="Plus icon"
                  height={18}
                  width={18}
                />
                <span className="font-semibold text-primary">New note</span>
              </Link>
            </button>
          </div>
          <div className="flex flex-col gap-2">
            <h2 className="px-4 text-sm font-semibold">Folders</h2>
            <Folders />
          </div>
          <div className="flex flex-col gap-2">
            <h2 className="px-4 text-sm font-semibold">More</h2>
            <More />
          </div>
        </nav>
        <main className="basis-full flex">{children}</main>
      </body>
    </html>
  );
}
